# Generated by Django 3.2 on 2022-08-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='адрес места')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='долгота')),
                ('lattitude', models.FloatField(blank=True, null=True, verbose_name='широта')),
                ('geodata_update_date', models.DateTimeField(auto_now=True, db_index=True, verbose_name='дата обновления координат')),
            ],
            options={
                'verbose_name': 'место',
                'verbose_name_plural': 'места',
            },
        ),
    ]
