# Generated by Django 3.2 on 2022-08-17 18:28

# from django.core.validators import MinValueValidator
from django.db import migrations, models


def add_order_item_cost(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    order_items = OrderItem.objects.all()
    for item in order_items.iterator():
        item.cost = item.product.price * item.quantity
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_rename_item_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cost',
            field=models.DecimalField(
                'стоимость',
                max_digits=8,
                decimal_places=2,
                null=True,
            )
        ),
        migrations.RunPython(add_order_item_cost),
    ]
