# Generated by Django 3.2 on 2022-08-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_alter_orderitem_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(1, 'необработанный'), (2, 'в сборке'), (3, 'в доставке'), (4, 'выполнен')], db_index=True, default=1, max_length=2, verbose_name='статус заказа'),
        ),
    ]
