# Generated by Django 3.2 on 2022-08-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(1, 'Необработанный'), (2, 'В сборке'), (3, 'В доставке'), (4, 'Выполнен')], db_index=True, default='Необработанный', max_length=2, verbose_name='статус заказа'),
        ),
    ]
