# Generated by Django 3.2 on 2022-08-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Необработанный'), ('2', 'В сборке'), ('3', 'В доставке'), ('4', 'Выполнен')], db_index=True, default='1', max_length=2, verbose_name='статус заказа'),
        ),
    ]
