# Generated by Django 3.2 on 2022-08-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_auto_20220818_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('1', 'Электронно'), ('2', 'Наличностью')], db_index=True, default='1', max_length=2, verbose_name='способ оплаты'),
        ),
    ]
