# Generated by Django 3.2 on 2022-08-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('1', 'Электронно'), ('2', 'Наличностью'), ('3', 'Не выбран')], db_index=True, default='3', max_length=2, verbose_name='способ оплаты'),
        ),
    ]
