# Generated by Django 3.2 on 2022-09-04 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_rename_restaurant_order_cooking_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_items', to='foodcartapp.product', verbose_name='товар'),
        ),
    ]
